### ISSUE TITLE
Slow points when harvesting

### ISSUE THREAD

**Issue by cofiem** [QutEcoacoustics/baw-server#212]
AudioRecordingsController#create (56%)
AudioRecordingsController#update_status (42%)

**Comment by atruskie** [comment]
Also extremely high CPU on database.

Need to investigate what part of the rails / queries are causing the high CPU

**Comment by cofiem** [comment]
Web response time is mainly db: 3270ms per request.
web request throughput maxed at 141 rpm.

**Comment by cofiem** [comment]
50GC runs per 100 tranactions seems silly - that's every 2nd transaction
make 1000 object,s destroy a 1000 objects etc...
1.5M objects

**Comment by cofiem** [comment]
harvest jobs go from 48s average to 73s average
