### ISSUE TITLE
Resolve resque polling errors

### ISSUE THREAD

**Issue by cofiem** [QutEcoacoustics/baw-server#217]
HEAD `/audio_recordings/267292/media.mp3?end_offset=2490&start_offset=2460`
HEAD `/audio_recordings/267292/media.png?end_offset=2490&start_offset=2460`

```
A CustomErrors::AudioGenerationError occurred in media#show:

  Resque did not complete media request within 120 seconds, result was 'queued'.
  lib/modules/media_poll.rb:98:in `poll_resque'
```

**Comment by cofiem** [comment]
It would be really nice to fix this... so many error emails...

**Comment by cofiem** [comment]
These errors are actually reflective of jobs with 'queued' status in redis. So what is causing these jobs to not be processed?

**Comment by cofiem** [comment]
Clearing all completed statuses gives 'Internal Server Error' at http://baw.ecosounds.org/job_queue_status/statuses/clear/completed

**Comment by atruskie** [comment]
Closing since we have made a lot of reliability changes recently and other more specific issues have addressed the root cause
