### ISSUE TITLE
Remove timezone configuration for brisbane

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#24]
Assigning the default timezone to the site as Brisbane (10+) as in (e2435cbe76e0088601fa202cab5ab9abb6c7b75d)[https://github.com/QutBioacoustics/baw-server/blob/e2435cbe76e0088601fa202cab5ab9abb6c7b75d/config/application.rb#L38] is terrible practice.

It was done to meet time constraints and so that old legacy problems were not a problem.

Removing this assumption will affect #22 and #23

**Comment by cofiem** [comment]
Based on tests done while adding site and user time zone settings ( https://github.com/QutBioacoustics/baw-server/pull/121 ), removing this setting will not affect accessing audio files.

**Comment by atruskie** [comment]
Good it won't affect. 

Still think this setting should removed/set to UTC anyway as it should now be redundant?

**Comment by cofiem** [comment]
set to UTC, yes. So, that will be 'server time', users will see things in the time zone they set.
