### ISSUE TITLE
Database schema change to allow datasets

### ISSUE THREAD

**Issue by peichins** [QutEcoacoustics/baw-server#344]
The proposed relational model is illustrated here
https://www.lucidchart.com/documents/edit/1c37dd44-7552-44a0-aea4-c03bf74ccdc4
Note: only the relations coloured in orange are required for this issue
- datasets
- dataset_items
- progress_events

---

- [x] Use console to create migrations 
- [x] Use rails console to create models
- [x] Double check models match desired schema
- [x] Add validation and user stamping to model files
- [x] Double check migrations match desired schema
  - Ensure appropriate secondary indices are added
- [x] Run the database migrations
- [x] Create unit test factory methods for new models
- [x] Create model specs for new models

**Comment by atruskie** [comment]
Additional notes:

- Database migration will need to add a seed value to the datasets table: The `Default` dataset.
- Datasets table should have `created` and `updated` user stamps
- I added a todo list to the main issue to guide the task

**Comment by atruskie** [comment]
Closed in: 94f403aa09bc324f6c5de1662c7ac355fd43255d, 866605de6cd8b40b8bf30ca20191ddbcf4c1a117, and 1428325894db1259d829f66a35569b0e1081b9cf
