### ISSUE TITLE
Implement Datasets API endpoints

### ISSUE THREAD

**Issue by peichins** [QutEcoacoustics/baw-server#345]
Implement the following 5 endpoints for the new dataset and datset_items models. 

- Controller: `DatasetsController`
  - `/datasets` (`GET` & `:index`, `POST & `:create`)
  - `/datasets/filter` (`GET` & `:filter`)
  - `/datasets/{dataset_id}` (`GET` & `:show`, `PUT & `:update`, `DELETE` & `:destroy`)
- Controller: `DatasetItems`
  - `/datasets/{dataset_id}/items` (`GET` & `:index`, `POST & `:create`)
  - `/datasets/{dataset_id}/items/filter`  (`GET` & `:filter`)
  - `/datasets/{dataset_id}/items/{dataset_items_id}`  (`GET` & `:show`, `PUT & `:update`, `DELETE` & `:destroy`)
  - ~~`/datasets/{dataset_id}/next`~~

All of these except `/datasets/{dataset_id}/next` will have versions for GET POST PUT and DELETE

~~ `/datasets/{dataset_id}/next` will be GET and will return the next page of items in the dataset. ~~
The _next_ route may not be needed as our standard API should support paging all by itself.

---

- [x] Make controllers for Datasets and Datasets items (can use rails console)
- [x] Ensure controller definitions match the idioms found in our existing controllers
- [ ] Implement a virtual column in our filtering API for ordering dataset items
  - Eventually, we'll support multiple algorithms, see #347 
  - For this issue, we're only going to implement an _incremental_ algorithm - as in sort by `dataset_item.id`
- [x] Add acceptance specs to cover all routes and user combinations
- [ ] Add appropriate documentation to our Wiki about these new endpoints

**Comment by atruskie** [comment]
Additional notes:

- I've added additional detail to the body of this issue to guide progress
- Note we haven't defined the following properties yet for datasets or dataset items
  - Datasets
    - Destroyable? (yes, no, or soft?)
    - Immutable?
    - Security? (create, edit, delete, and where do they fit in with our existing project-based security?)
  - Dataset Items
    - Destroyable?
    - Immutable?
    - Security?
- I've also added a todo list to the body of the issue
