### ISSUE TITLE
Update database schema to accommodate citizen science

### ISSUE THREAD

**Issue by peichins** [QutEcoacoustics/baw-server#346]
The proposed relational model is illustrated here
https://www.lucidchart.com/documents/edit/1c37dd44-7552-44a0-aea4-c03bf74ccdc4
Note: the relations in green are needed for citizen science. 
- citizen_science_projects
- citizen_science_labels
- citizen_science_labelings

This is low priority and may be subject to change.

**Comment by cofiem** [comment]
The PR that closed this issue does not implement it? I think you meant #344

**Comment by atruskie** [comment]
@peichins please add the updated textual schema that we discussed yesterday

**Comment by peichins** [comment]
The tables/models are 
- Studies
  - Relationships
    - Belongs to Dataset
    - Has and belongs to many Questions
    - Has many Responses
  - Attributes (other than id and FKs)
    - name
- Questions
  - Relationships
    - Has and belongs to many Studies
    - Has many Responses
  - Attributes (other than id and FKs)
    - text
    - data (JSON)
- Responses
  - Relationships
    - Belongs to Question
    - Belongs to Study
    - Belongs to DatasetItem
    - Belongs to Creator
  - Attributes (other than id and FKs)
    - data (JSON)

(see diagram for more details https://www.lucidchart.com/invitations/accept/f3447066-7f9f-47bd-ae56-11a1b3891907)

**Study** relates one or more questions to a dataset.

**Question**
- contains the wording of the question that the user will be answering. 
- Is associated with one or more studies (many to many). Questions may be reused by different studies (i.e. applied to different datasets), and there might be more than one question per study. 
- has a ‘data’ field that will contain json encoded information that is used to present the question to users. This ‘data’ may include 
  - any labels that could be applied to a dataset item, 
  - example annotations (library items) that could assist the user
  - Images that should be shown alongside the question or examples
- Has a “text” which is designed to store the wording of the question

**Response** contains the answer to a question for a particular dataset item. 
- Each response will be associated with a question record. 
- The data of the response will be stored as a json blob. 
  - The JSON blob should make sense in the context of the question, however this is not validated by the rails app and is the responsibility of the client.
  - We will define a JSON schema for responses that we validate against. This doesn’t validate that the response answers its question, only that it conforms to a certain structure. 
    - todo: define this schema
- Each response will be associated with a study. 
  - This allows both questions and datasets to be used by multiple studies. 
  - It also allows easier querying on responses for a particular study. 
  - This also opens one avenue for logical inconsistencies in associations (e.g. response is associated with question A and study B, but question A is not associated with study B). 
    - **inconsistencies should be avoided through validation rules in the model.**
