### ISSUE TITLE
Implement Progress API

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#348]
Implement the following endpoints for the new progress models. 

- Controller: `ProgressEvents`
  - `/datasets/{dataset_id}/progress_events` (`GET` & `:index`, `POST` & `:create`)
  - `/datasets/{dataset_id}/progress_events/filter`  (`GET` & `:filter`)
  - `/datasets/{dataset_id}/progress_events/{progress_events_id}`  (`GET` & `:show`, `DELETE` & `:destroy`)
- Controller: `ProgressEventsSummary`
  - `/datasets/{dataset_id}/progress_events/summary` (`GET` & `:index`, `POST & `:filter`)  

Note: we will not support updating progress events

---

- [ ] Make controllers for ProgressEvents and ProgressEventsSummary items (can use rails console)
- [x] Ensure controller definitions match the idioms found in our existing controllers
- [x] Add acceptance specs to cover all routes and user combinations
- [x] Add appropriate documentation to our Wiki about these new endpoints
- [ ] Ensure creating new progress events for the `Default` dataset works automatically

**Comment by peichins** [comment]
Proposed permissions for progress events:
Update and Delete:
- Progress events are not updatable or deletable. 

Create
- Any user needs to be able to create progress events for the dataset item they are viewing/playing/annotating.  
- Currently, dataset items just inherit permissions from projects via 
project/site/audio_recording/dataset_item.  
- Proposal: A user can create a progress event with a given dataset_item_id if that dataset item belongs (indirectly) to a project they have read access on. 

View / index / filter
- Users may need to see progress of other uses on their projects. 
- Users may need to see their own progress. 
- Progress events will be used to sort dataset_items for citizen science projects. However, this should be done within the dataset_items filter response on the server, so it probably doesn't impact the index, view or filter permissions on progress events. 
- Proposal: Users have read access on progress events if
  - they belong indirectly to a project the user has read access on. 
    - Does this means everyone will be able to see everyone's activity on public projects?
  - they are the creator of the progress event. This should be a subset of the above anyway, unless access to a project is revoked.
