### ISSUE TITLE
Bug: NoMethodError occurred in dataset_items#create

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#366]
A NoMethodError occurred in dataset_items#create:

  undefined method `[]=' for nil:NilClass
  app/controllers/dataset_items_controller.rb:94:in `dataset_item_params'

- URL: https://staging.ecosounds.org/datasets/3/items
- HTTP Method: POST
- Parameters : {"format"=>"json", "controller"=>"dataset_items", "action"=>"create", "dataset_id"=>"3"}

```
-------------------------------
Backtrace:
-------------------------------

  app/controllers/dataset_items_controller.rb:94:in `dataset_item_params'
  app/controllers/dataset_items_controller.rb:53:in `create'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

**Comment by peichins** [comment]
This happened for a /datasets/3/items POST request send with no content. It was an invalid POST request. This should be caught and handled, with tests added to the spec.
