### ISSUE TITLE
Incorrect current page link when there are zero items 

### ISSUE THREAD

**Issue by peichins** [QutEcoacoustics/baw-server#378]
in filter requests, when there are zero items and therefore max_page = 0, the response includes a url to  current with query string parameter page=0.   I believe this behaviour was introduced at 44a2557dd2605ad28737c2e8158fcb185966b7c0 among many other changes, without much explanation. It seems more natural for the current page to be 1, even if there are zero items, or for there to be no 'current' url if there are zero items.

**Comment by atruskie** [comment]
I agree. The following should be our defined behaviour:

If there are no items then the paging object should be: `{page: 1, items: 25, total: 0, max_page: 1, next_link: null, current_link: ...&page=1, previous_link: null}`

Please ensure the wiki API specification is updated if needed.
