### ISSUE TITLE
Some site fields are not exposed in the API

### ISSUE THREAD

**Issue by peichins** [QutEcoacoustics/baw-server#406]
The site model only renders a small number of fields meaning it is not possible to include latitude and longitude in the filter projection. 

https://github.com/QutEcoacoustics/baw-server/blob/9e6bca814a6e25fb3473a7871a2fefd63b4b829a/app/models/site.rb#L178

```
filter:
{'filter': {'id': {'in': [1792, 1793, 1794, 1177, 1693, 1192, 1193, 1790, 1791, 1462, 1468, 1476, 1106, 1108, 1109, 1494, 1517, 1522, 1523, 1529, 2558, 2559]}}, 'projection': {'include': ['id', 'name', 'latitude', 'longitude']}}
response:
{'meta': {'status': 400, 'message': 'Bad Request', 'error': {'details': 'Filter parameters were not valid: Name must be in [:id, :name, :description], got latitude', 'info': None}}, 'data': None}
```

We should expose the latitude and longitude and possible other fields as well.

**Comment by Allcharles** [comment]
Another field left unexposed is the creatorId field. To Reproduce: https://staging.ecosounds.org/projects/1/sites/1.json
