### ISSUE TITLE
Create site route ignoring inputs

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#410]
# Create Site Route

Associated Page: https://staging.ecosounds.org/projects/17/sites/new
Route: `/projects/:projectId/sites`
Method: `POST`

Following body inputs are ignored:

- [ ] ~`locationObfuscated`~
- [x] `customLatitude` <- actual value is `latitude`
- [x] `customLongitude` <- actual value is `longitude`
- [x] `timezoneInformation` <- actual value is `tzinfo_tz`

**Comment by peichins** [comment]
The new site route is ok as is. Only the create route needs to be fixed

**Comment by atruskie** [comment]
@Allcharles what is the issue here?

Expected behaviour is that `latitude` and `longitude` are write only fields?

**Comment by Allcharles** [comment]
I think its been fixed already. This was mostly a question when I didn't understand how the model worked because it has separate values for output and input. Phil couldn't tell me the difference. I guess the underlying problem is the lack of documentation to inform users how things work.
