### ISSUE TITLE
Project route missing fields

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#425]
Route: `https://staging.ecosounds.org/projects/1`
Method: `GET`
Missing fields:

- `created_at`
- `updater_id`
- `updated_at`
- `owner_id`
- `access_level` (Potentially part of capabilities route)

**Comment by atruskie** [comment]
Also need to be able to filter by access_level

**Comment by Allcharles** [comment]
Specifically, filter by access_level for another user. Ie. Admin needs to find all projects another user has access to

**Comment by atruskie** [comment]
On review: I'm not sure what we mean by access level?

**Comment by Allcharles** [comment]
access level is the permissions a user has for the project, ie. Guest/Reader/Writer/Owner/Admin
