### ISSUE TITLE
Missing generic sites route

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#431]
Associated Page: https://staging.ecosounds.org/projects/4/edit_sites
Expected Route: `/sites`
Expected Method: `GET`
Expected Body:

- `site[]`

Expected Action:

- Should return a list of all sites
- For logged in users, should return list of all sites they have access to
- For guest users, should return unauthorized

**Comment by Allcharles** [comment]
@atruskie @peichins Part of this links into the https://staging.ecosounds.org/projects/1/edit_sites page. Should `/sites` display only the list of sites a user already has access to, or should it display all sites and make a request to the site owner for access. Once access is granted, what level of access is provided (Read/Write/Owner)? This may be a separate issue.

**Comment by atruskie** [comment]
`/sites` will only display sites a user already has access to.

Level of access is determined by the parent project. If it is in multiple projects, the highest level wins.

**Comment by Allcharles** [comment]
There also needs to be the ability to determine the list of sites another user has access to. For example, the admin needs to be able to view which sites a user has access to.
