### ISSUE TITLE
Missing type of tag route

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#441]
Associated Page: https://staging.ecosounds.org/admin/tags/new
Expected Route: `/tags/type_of_tags`?
Expected Body:

- `type_of_tag` list
  - `id`
  - `name`

DB seems to store these as plaintext so this route may be admin specific? I am unsure why it's a select menu in the admin console.

**Comment by atruskie** [comment]
Tag types are constrained list of strings - an enum. They don't have their own model, or their own route
