### ISSUE TITLE
Missing assign sites route

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#447]
Associated Page: https://staging.ecosounds.org/projects/26/edit_sites
Expected Route: ???
Expected Action: Should assign a site to a project. This is an admin only command.

**Comment by atruskie** [comment]
This one should be already implemented.

When you push the site model back to the API it can have a list of project ids. If you add more projects ids into that list then they'll be associated with more projects, vice versa with fewer ids.

Reopen if this does not work as expected.
