### ISSUE TITLE
Project short descriptions

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#486]
Add a short description (tagline) to the Project model. This should be editable by the user, less than 150/200 characters, and in plain-text (no markdown, no html). If a short description does not exist for the model, either generate a sanitized and stripped short description from the existing `description_html`, or leave as `nil`.

This short description will be used on the website when listing projects. Thus, it's an incentive for researchers to create small blurbs to attract attention to their project.

**Comment by atruskie** [comment]
Related to #298, #278, #289

**Comment by atruskie** [comment]
Closed in 7ecedaac87d58f32c83f84f04f0a109d415cca36 and ed49d77429914bfedc4270aef7b4660283c67935
