### ISSUE TITLE
Changes to support dev work

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#518]
- chrome has now enforced same site cookie policies. See https://blog.heroku.com/chrome-changes-samesite-cookie
  - i think that means i need to add `SameSite=none` to development environment
  - see https://github.com/rails/rails/pull/28297
- we need to add dev domain and ip to hosts config. @Allcharles has a commit in a working branch that does this. Post the diff please?

At @Allcharles  can you also post the detail of the same site cookie issue?

Potentially this is all ignored if we actually implement proper auth

**Comment by Allcharles** [comment]
Diff is here: https://github.com/QutEcoacoustics/baw-server/commit/972164f14c1acad91d7896689d80a724ce33dfc0

Error for cookie is the following:

```
set-cookie: _awb_session=[cookie_details]; path=/; HttpOnly

This Set-Cookie didn't specify a "SameSite" attribute, was defaulted to "SameSite=Lax", and was blocked because it 
came from a cross-site response which was not the response to a top-level navigation. This response is considered 
cross-site because the URL has a different scheme than the current site.
```

**Comment by atruskie** [comment]
Some changes were included in github.com/QutEcoacoustics/baw-server/blob/master/config/initializers/new_framework_defaults_6_1.rb#L28

https://github.com/QutEcoacoustics/baw-server/commit/f51bb0bf6961bd5bf1b08a7b864c9107b886b38a

The [rails_same_site_cookie gem will only work until 2022/(https://github.com/pschinis/rails_same_site_cookie)

**Comment by atruskie** [comment]
Some changes were included in github.com/QutEcoacoustics/baw-server/blob/master/config/initializers/new_framework_defaults_6_1.rb#L28

https://github.com/QutEcoacoustics/baw-server/commit/f51bb0bf6961bd5bf1b08a7b864c9107b886b38a

The rails_same_site_cookie gem will only work
